### ISSUE TITLE
Typos and Hyper-parameters

### ISSUE THREAD

**Issue by tedzhouhk** [CunchaoZ/CyGNet#3]
Dear CunchaoZ,

Thanks for providing the open-source code for your fantastic AAAI'21 work. When I try to run your code, I find there are two typos

1. get_historical_vocabulary.py line 59: svae_dir_sub
2. class link_prediction in link_prediction.py self.num_times is not defined

After fixing these typos, I was able to run the code. However, I am having trouble reproducing the numbers reported in the paper. Could you release the hyper-parameters used in training?

Thanks!

**Comment by CunchaoZ** [comment]
Thank you for your question, I have modified the code and README. 
Due to a personal oversight on my part, the previous version of the paper included only predicted object entities in the experiments. I have corrected this error and have uploaded the [latest version of the paper](https://arxiv.org/pdf/2012.08492.pdf).

**Comment by CunchaoZ** [comment]
Thank you for your question, I have modified the code and README.
Due to a personal oversight on my part, the previous version of the paper included only predicted object entities in the experiments. I have corrected this error and have uploaded the [latest version of the paper](https://arxiv.org/pdf/2012.08492.pdf).

**Comment by CunchaoZ** [comment]
Thank you for your question, I have modified the code and README.
The previous version of the paper included only predicted object entities in the experiments. I have corrected this error and have uploaded the [latest version of the paper](https://arxiv.org/pdf/2012.08492.pdf).

**Comment by tedzhouhk** [comment]
Thanks for the quick reply!
